### ISSUE TITLE
Usage of ArrayList in constructor makes it harder to use.

### ISSUE THREAD

**Issue by leCandas** [makstron/TCharts#1]
I want to choose list implementation when creating chart data. Please use just List interface rather ArrayList.

`public ChartData(ArrayList<String> keys, ArrayList<String> names, ArrayList<Integer> colors, ArrayList<ChartItem> items)`

**Comment by makstron** [comment]
Hi.
Thank you =)
I have done it in the last (0.9.2) version.

**Comment by leCandas** [comment]
@makstron don't forget ChartItem :)

**Comment by leCandas** [comment]
Thanks for the code & fast response. 
I am giving it a try on my app.

**Comment by makstron** [comment]
Completely forgot 
Done =)

Write me about any troubles or suggestion when you try it
Have a nice day =)

**Comment by leCandas** [comment]
@makstron there are some bugs I face at the moment that could be related to my use case indeed.

I am trying to put 2 sensor outputs into the chart. 
One is int the other is float. The graph does not support floats where I just cast it to int. (Could be a good improvement to add float support)

My sample rate for sensors is 1 second and recording length dependent on how long that user wants to record. At this point, I see widget crashes if the data set is quite small (5 sec for example). With a considerably long recording (30 sec), it loads but crashes if I try to change resolution. I also failed when I try to load the cart with long recordings like 1 min.

`    java.lang.IndexOutOfBoundsException: Index: 16, Size: 9
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.klim.tcharts.views.DetailView.onTimeLineChanged(DetailView.java:565)
        at com.klim.tcharts.views.SelectedWindow.sendTimeLineChanged(SelectedWindow.java:190)
        at com.klim.tcharts.views.SelectedWindow.actionMove(SelectedWindow.java:183)
        at com.klim.tcharts.views.SelectedWindow.onTouchEvent(SelectedWindow.java:110)
        at com.klim.tcharts.views.NavigationView.onTouchEvent(NavigationView.java:198)
        at com.klim.tcharts.TChart.onTouchEvent(TChart.java:324)
        at android.view.View.dispatchTouchEvent(View.java:13503)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:613)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1933)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4147)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:559)
        at android.view.View.dispatchPointerEvent(View.java:13766)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5824)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5619)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5063)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootIm`

Also for my case, I am not happy with date formatting since I care about seconds instead day and date.

Scrolling works fine.

I would be happy to provide more use cases if you want.

**Comment by makstron** [comment]
It was developed for a big range of time. 
About float. Exists many different ways to format float. Formatting on the fly can make it slower.

I will think about a short period of time and other data types. It will be great features.

Can you send me your raw data and I will fix this error as fast I can?

**Comment by leCandas** [comment]
Here you go:

> 
E/SHORT:: {"colors":[-16711936,-65536],"items":[{"maxValue":1012,"time":1618951646915,"values":[1012,87]},{"maxValue":1012,"time":1618951647916,"values":[1012,87]}],"keys":["PPFD","DLI"],"maxValueInLine":[0,0],"names":["PPFD","DLI"]}


E/LONG:: {"colors":[-16711936,-65536],"items":[{"maxValue":1012,"time":1618951646915,"values":[1012,87]},{"maxValue":1012,"time":1618951647916,"values":[1012,87]},{"maxValue":1012,"time":1618951717988,"values":[1012,87]},{"maxValue":1012,"time":1618951718990,"values":[1012,87]},{"maxValue":1012,"time":1618951719992,"values":[1012,87]},{"maxValue":1012,"time":1618951720996,"values":[1012,87]},{"maxValue":1012,"time":1618951721999,"values":[1012,87]},{"maxValue":1012,"time":1618951723001,"values":[1012,87]},{"maxValue":1012,"time":1618951724003,"values":[1012,87]},{"maxValue":1012,"time":1618951725005,"values":[1012,87]},{"maxValue":1012,"time":1618951726008,"values":[1012,87]},{"maxValue":1012,"time":1618951727011,"values":[1012,87]},{"maxValue":1012,"time":1618951728012,"values":[1012,87]},{"maxValue":1012,"time":1618951729013,"values":[1012,87]},{"maxValue":1012,"time":1618951730017,"values":[1012,87]},{"maxValue":1012,"time":1618951731021,"values":[1012,87]},{"maxValue":995,"time":1618951732023,"values":[995,85]},{"maxValue":758,"time":1618951733023,"values":[758,65]},{"maxValue":541,"time":1618951734025,"values":[541,46]},{"maxValue":376,"time":1618951735032,"values":[376,32]},{"maxValue":236,"time":1618951736049,"values":[236,20]},{"maxValue":159,"time":1618951737052,"values":[159,13]},{"maxValue":70,"time":1618951738055,"values":[70,6]},{"maxValue":45,"time":1618951739059,"values":[45,3]},{"maxValue":283,"time":1618951740059,"values":[283,24]},{"maxValue":268,"time":1618951741062,"values":[268,23]},{"maxValue":273,"time":1618951742064,"values":[273,23]},{"maxValue":731,"time":1618951743065,"values":[731,63]},{"maxValue":863,"time":1618951744071,"values":[863,74]},{"maxValue":754,"time":1618951745075,"values":[754,65]},{"maxValue":725,"time":1618951746077,"values":[725,62]},{"maxValue":919,"time":1618951747080,"values":[919,79]},{"maxValue":1003,"time":1618951748083,"values":[1003,86]},{"maxValue":923,"time":1618951749084,"values":[923,79]},{"maxValue":742,"time":1618951750086,"values":[742,64]},{"maxValue":640,"time":1618951751088,"values":[640,55]},{"maxValue":565,"time":1618951752093,"values":[565,48]},{"maxValue":438,"time":1618951753095,"values":[438,37]},{"maxValue":267,"time":1618951754096,"values":[267,23]},{"maxValue":203,"time":1618951755100,"values":[203,17]},{"maxValue":332,"time":1618951756106,"values":[332,28]},{"maxValue":510,"time":1618951757109,"values":[510,44]},{"maxValue":666,"time":1618951758111,"values":[666,57]},{"maxValue":478,"time":1618951759114,"values":[478,41]},{"maxValue":455,"time":1618951760116,"values":[455,39]},{"maxValue":686,"time":1618951761120,"values":[686,59]},{"maxValue":587,"time":1618951762122,"values":[587,50]},{"maxValue":358,"time":1618951763123,"values":[358,30]},{"maxValue":951,"time":1618951764124,"values":[951,82]},{"maxValue":1012,"time":1618951765136,"values":[1012,87]},{"maxValue":1012,"time":1618951766138,"values":[1012,87]},{"maxValue":1012,"time":1618951767140,"values":[1012,87]}],"keys":["PPFD","DLI"],"maxValueInLine":[0,0],"names":["PPFD","DLI"]}

**Comment by makstron** [comment]
I have fixed a bug with small data (0.9.4) and I am working to add an option for formate data/time.
